/*
 * @Date: 2025-11-25
 * @LastEditors: Auto-generated by TableDefinitionGenerator
 * @LastEditTime: 2025-11-25
 * @FilePath: ./config/tableDefinitions.js
 * @Description: 自动生成的表结构定义 - 请勿手动修改
 */

/**
 * 系统必需的表结构定义
 * 由 TableDefinitionGenerator 自动从模型生成
 */
const tableDefinitions = {
  "table_mappings": {
    "name": "table_mappings",
    "description": "TableMapping 表",
    "columns": [
      {
        "name": "id",
        "type": "INTEGER",
        "primaryKey": true,
        "autoIncrement": true,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "table_name",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "原始表名"
      },
      {
        "name": "hash_value",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": true,
        "defaultValue": null,
        "comment": "哈希值(SHA256)"
      },
      {
        "name": "original_file_name",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "原始文件名"
      },
      {
        "name": "column_count",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": 0,
        "comment": "列数"
      },
      {
        "name": "row_count",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": 0,
        "comment": "行数"
      },
      {
        "name": "header_row",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": 0,
        "comment": "表头行号（从0开始）"
      },
      {
        "name": "column_definitions",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "列定义信息"
      },
      {
        "name": "form_config",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "表单配置信息（JSON Schema格式）"
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "updated_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": {},
        "comment": null
      }
    ],
    "indexes": [
      {
        "name": "idx_table_mappings_hash_value_unique",
        "columns": [
          "hash_value"
        ],
        "unique": true
      },
      {
        "name": "table_mappings_hash_value",
        "columns": [
          "hash_value"
        ],
        "unique": true
      },
      {
        "name": "table_mappings_table_name",
        "columns": [
          "table_name"
        ],
        "unique": false
      },
      {
        "name": "table_mappings_created_at",
        "columns": [
          "created_at"
        ],
        "unique": false
      }
    ]
  },
  "users": {
    "name": "users",
    "description": "User 表",
    "columns": [
      {
        "name": "id",
        "type": "INTEGER",
        "primaryKey": true,
        "autoIncrement": true,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "username",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": true,
        "defaultValue": null,
        "comment": "用户名"
      },
      {
        "name": "email",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": true,
        "defaultValue": null,
        "comment": "邮箱"
      },
      {
        "name": "password_hash",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "密码哈希"
      },
      {
        "name": "display_name",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "显示名称"
      },
      {
        "name": "role",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": "user",
        "comment": "用户角色"
      },
      {
        "name": "is_active",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": true,
        "comment": "是否激活"
      },
      {
        "name": "last_login",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "最后登录时间"
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "updated_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": {},
        "comment": null
      }
    ],
    "indexes": [
      {
        "name": "idx_users_username_unique",
        "columns": [
          "username"
        ],
        "unique": true
      },
      {
        "name": "idx_users_email_unique",
        "columns": [
          "email"
        ],
        "unique": true
      },
      {
        "name": "users_username",
        "columns": [
          "username"
        ],
        "unique": true
      },
      {
        "name": "users_email",
        "columns": [
          "email"
        ],
        "unique": true
      },
      {
        "name": "users_role",
        "columns": [
          "role"
        ],
        "unique": false
      },
      {
        "name": "users_created_at",
        "columns": [
          "created_at"
        ],
        "unique": false
      }
    ]
  },
  "table_logs": {
    "name": "table_logs",
    "description": "TableLog 表",
    "columns": [
      {
        "name": "id",
        "type": "INTEGER",
        "primaryKey": true,
        "autoIncrement": true,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "operation_type",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "table_name",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "table_hash",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "record_id",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "old_data",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "new_data",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "description",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "user_id",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "username",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "operation_time",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "is_rolled_back",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": false,
        "comment": null
      },
      {
        "name": "rollback_time",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "rollback_user_id",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "rollback_username",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "rollback_description",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "ip_address",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "user_agent",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "updated_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      }
    ],
    "indexes": [
      {
        "name": "table_logs_operation_type",
        "columns": [
          "operation_type"
        ],
        "unique": false
      },
      {
        "name": "table_logs_table_name",
        "columns": [
          "table_name"
        ],
        "unique": false
      },
      {
        "name": "table_logs_table_hash",
        "columns": [
          "table_hash"
        ],
        "unique": false
      },
      {
        "name": "table_logs_record_id",
        "columns": [
          "record_id"
        ],
        "unique": false
      },
      {
        "name": "table_logs_user_id",
        "columns": [
          "user_id"
        ],
        "unique": false
      },
      {
        "name": "table_logs_operation_time",
        "columns": [
          "operation_time"
        ],
        "unique": false
      },
      {
        "name": "table_logs_is_rolled_back",
        "columns": [
          "is_rolled_back"
        ],
        "unique": false
      }
    ]
  },
  "form_definitions": {
    "name": "form_definitions",
    "description": "FormDefinition 表",
    "columns": [
      {
        "name": "id",
        "type": "TEXT",
        "primaryKey": true,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "form_id",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": true,
        "defaultValue": null,
        "comment": "表单唯一标识"
      },
      {
        "name": "name",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "表单名称"
      },
      {
        "name": "description",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "表单描述"
      },
      {
        "name": "table_mapping",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "关联的数据表哈希"
      },
      {
        "name": "definition",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "表单定义JSON"
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "updated_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      }
    ],
    "indexes": [
      {
        "name": "idx_form_definitions_form_id_unique",
        "columns": [
          "form_id"
        ],
        "unique": true
      }
    ]
  },
  "form_hooks": {
    "name": "form_hooks",
    "description": "FormHook 表",
    "columns": [
      {
        "name": "id",
        "type": "TEXT",
        "primaryKey": true,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "form_id",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "关联的表单ID"
      },
      {
        "name": "type",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "Hook类型: javascript, http, database, conditional"
      },
      {
        "name": "trigger_type",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "触发时机: beforeSubmit, afterSubmit, onError"
      },
      {
        "name": "config",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "Hook配置JSON"
      },
      {
        "name": "enabled",
        "type": "INTEGER",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": true,
        "comment": "是否启用"
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "updated_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      },
      {
        "name": "form_id",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": null
      }
    ],
    "indexes": []
  },
  "form_submissions": {
    "name": "form_submissions",
    "description": "FormSubmission 表",
    "columns": [
      {
        "name": "id",
        "type": "TEXT",
        "primaryKey": true,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": {},
        "comment": null
      },
      {
        "name": "form_id",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "关联的表单ID"
      },
      {
        "name": "submission_data",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": "原始提交数据"
      },
      {
        "name": "processed_data",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "处理后的数据"
      },
      {
        "name": "status",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": "pending",
        "comment": "处理状态: pending, success, error"
      },
      {
        "name": "error_message",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": true,
        "unique": false,
        "defaultValue": null,
        "comment": "错误信息"
      },
      {
        "name": "created_at",
        "type": "TEXT",
        "primaryKey": false,
        "autoIncrement": false,
        "allowNull": false,
        "unique": false,
        "defaultValue": null,
        "comment": null
      }
    ],
    "indexes": []
  }
};

module.exports = {
  tableDefinitions
};
