/*
 * @Date: 2025-11-25 19:16:00
 * @LastEditors: CZH
 * @LastEditTime: 2025-11-25 19:18:02
 * @FilePath: /lowCode_excel/backend/utils/tableDefinitionGenerator.js
 * @Description: 表结构生成器 - 根据模型定义生成数据库特定的表结构
 */

const ModelParser = require('./modelParser');

/**
 * 表结构生成器类
 * 负责根据模型定义生成数据库特定的表结构定义和SQL语句
 */
class TableDefinitionGenerator {
  /**
   * 从模型集合生成表结构定义
   * @param {Object} models 模型对象集合
   * @param {string} dialect 数据库类型 ('sqlite' | 'mysql')
   * @returns {Object} 表结构定义对象
   */
  static generateFromModels(models, dialect = 'sqlite') {
    return ModelParser.parseAllModels(models, dialect);
  }
  
  /**
   * 生成表的SQL创建语句
   * @param {Object} tableDefinition 表结构定义
   * @param {string} dialect 数据库类型
   * @returns {string} SQL创建语句
   */
  static generateCreateTableSQL(tableDefinition, dialect = 'sqlite') {
    const columns = tableDefinition.columns.map(col => {
      let columnDef = dialect === 'sqlite' 
        ? `"${col.name}" ${col.type}`
        : `\`${col.name}\` ${col.type}`;
      
      if (col.primaryKey) {
        columnDef += ' PRIMARY KEY';
        if (col.autoIncrement) {
          columnDef += dialect === 'sqlite' ? ' AUTOINCREMENT' : ' AUTO_INCREMENT';
        }
      }
      
      if (col.unique) {
        columnDef += ' UNIQUE';
      }
      
      if (!col.allowNull) {
        columnDef += ' NOT NULL';
      }
      
      if (col.defaultValue !== null && col.defaultValue !== undefined) {
        if (typeof col.defaultValue === 'string' && col.defaultValue !== 'CURRENT_TIMESTAMP') {
          columnDef += ` DEFAULT '${col.defaultValue}'`;
        } else {
          columnDef += ` DEFAULT ${col.defaultValue}`;
        }
      }
      
      // 添加列注释（MySQL支持）
      if (dialect === 'mysql' && col.comment) {
        columnDef += ` COMMENT '${col.comment}'`;
      }
      
      return columnDef;
    }).join(',\n  ');

    let sql = dialect === 'sqlite' 
      ? `CREATE TABLE IF NOT EXISTS "${tableDefinition.name}" (\n  ${columns}\n)`
      : `CREATE TABLE IF NOT EXISTS \`${tableDefinition.name}\` (\n  ${columns}\n)`;

    // 添加表注释（MySQL支持）
    if (dialect === 'mysql' && tableDefinition.description) {
      sql += ` COMMENT '${tableDefinition.description}'`;
    }

    return sql + ';';
  }
  
  /**
   * 生成表的索引创建语句
   * @param {Object} tableDefinition 表结构定义
   * @param {string} dialect 数据库类型
   * @returns {string[]} 索引创建语句数组
   */
  static generateIndexSQL(tableDefinition, dialect = 'sqlite') {
    if (!tableDefinition.indexes || tableDefinition.indexes.length === 0) {
      return [];
    }

    return tableDefinition.indexes.map(index => {
      const columns = index.columns.map(col => 
        dialect === 'sqlite' ? `"${col}"` : `\`${col}\``
      ).join(', ');
      
      const uniqueKeyword = index.unique ? 'UNIQUE ' : '';
      
      if (dialect === 'sqlite') {
        return `CREATE ${uniqueKeyword}INDEX IF NOT EXISTS "${index.name}" ON "${tableDefinition.name}" (${columns});`;
      } else {
        return `CREATE ${uniqueKeyword}INDEX IF NOT EXISTS \`${index.name}\` ON \`${tableDefinition.name}\` (${columns});`;
      }
    });
  }
  
  /**
   * 生成所有表的SQL语句
   * @param {Object} tableDefinitions 所有表的结构定义
   * @param {string} dialect 数据库类型
   * @returns {Object} 包含所有SQL语句的对象
   */
  static generateAllSQL(tableDefinitions, dialect = 'sqlite') {
    const sqlStatements = {
      createTables: {},
      createIndexes: {}
    };
    
    for (const [tableName, tableDef] of Object.entries(tableDefinitions)) {
      sqlStatements.createTables[tableName] = this.generateCreateTableSQL(tableDef, dialect);
      sqlStatements.createIndexes[tableName] = this.generateIndexSQL(tableDef, dialect);
    }
    
    return sqlStatements;
  }
  
  /**
   * 保存表结构定义到文件
   * @param {Object} definitions 表结构定义
   * @param {string} filePath 文件路径
   */
  static saveTableDefinitions(definitions, filePath) {
    const fs = require('fs');
    const path = require('path');
    
    // 确保目录存在
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    
    // 生成文件内容 - 使用简单的JSON格式
    const content = `/*
 * @Date: ${new Date().toISOString().split('T')[0]}
 * @LastEditors: Auto-generated by TableDefinitionGenerator
 * @LastEditTime: ${new Date().toISOString().split('T')[0]}
 * @FilePath: ${filePath}
 * @Description: 自动生成的表结构定义 - 请勿手动修改
 */

/**
 * 系统必需的表结构定义
 * 由 TableDefinitionGenerator 自动从模型生成
 */
const tableDefinitions = ${JSON.stringify(definitions, null, 2)};

module.exports = {
  tableDefinitions
};
`;
    
    fs.writeFileSync(filePath, content, 'utf8');
    console.log('✅ 表结构定义已保存到: ' + filePath);
  }
  
  /**
   * 验证表结构定义是否与模型一致
   * @param {Object} tableDefinitions 表结构定义
   * @param {Object} models 模型集合
   * @returns {Object} 验证结果
   */
  static validateTableDefinitions(tableDefinitions, models) {
    const validation = {
      success: true,
      errors: [],
      warnings: []
    };
    
    const modelDefinitions = this.generateFromModels(models);
    
    // 检查表数量是否一致
    const tableNames = Object.keys(tableDefinitions);
    const modelTableNames = Object.keys(modelDefinitions);
    
    if (tableNames.length !== modelTableNames.length) {
      validation.success = false;
      validation.errors.push('表数量不一致: 定义中有 ' + tableNames.length + ' 个表，模型中有 ' + modelTableNames.length + ' 个表');
    }
    
    // 检查每个表的结构
    for (const tableName of tableNames) {
      if (!modelDefinitions[tableName]) {
        validation.warnings.push('表 ' + tableName + ' 在模型定义中不存在');
        continue;
      }
      
      const tableDef = tableDefinitions[tableName];
      const modelDef = modelDefinitions[tableName];
      
      // 检查列数量
      if (tableDef.columns.length !== modelDef.columns.length) {
        validation.success = false;
        validation.errors.push('表 ' + tableName + ' 列数量不一致: 定义中有 ' + tableDef.columns.length + ' 列，模型中有 ' + modelDef.columns.length + ' 列');
      }
      
      // 检查列定义
      for (const modelCol of modelDef.columns) {
        const tableCol = tableDef.columns.find(col => col.name === modelCol.name);
        if (!tableCol) {
          validation.success = false;
          validation.errors.push('表 ' + tableName + ' 缺少列: ' + modelCol.name);
        } else if (tableCol.type !== modelCol.type) {
          validation.warnings.push('表 ' + tableName + ' 列 ' + modelCol.name + ' 类型不一致: 定义中为 ' + tableCol.type + '，模型中为 ' + modelCol.type);
        }
      }
    }
    
    return validation;
  }
}

module.exports = TableDefinitionGenerator;
