services:
  # 前端服务
  frontend:
    image: annual-leave-frontend:latest
    container_name: annual-leave-frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # 后端服务（使用 SQLite）
  backend:
    image: annual-leave-backend:latest
    container_name: annual-leave-backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_TYPE=sqlite
      - SQLITE_DB_PATH=/app/data/annual_leave.db
      - LOCAL_RUN=true
    volumes:
      - backend-uploads:/app/uploads
      - sqlite-data:/app/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# 网络配置
networks:
  app-network:
    driver: bridge

# 卷配置
volumes:
  backend-uploads:
    driver: local
  sqlite-data:
    driver: local
